name: Cloudbase-Init functional tests

on: [push, pull_request]

jobs:
  build-windows-functional:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.11"]
        architecture: ["x64"]
        cloud: ["empty"]
        upper-constraints: ["https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt"]
        test-resources: ["https://github.com/ader1990/cloudbase-init-test-resources-1"]

    steps:
    - name: Checkout cloudbase-init repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Download external dependencies
      shell: cmd
      run: |
        git clone ${{ matrix.test-resources }} test-resources
        python -W ignore -m pip install --upgrade pip
    - name: Install Cloudbase-Init
      shell: cmd
      run: |
        python -W ignore -m pip install -c ${{ matrix.upper-constraints }} -U --force-reinstall -r requirements.txt
        python -W ignore -m pip install .
    - name: Run Cloudbase-Init functional tests
      shell: powershell
      run: |
        try {
            & cmd /c "cloudbase-init.exe --noreset_service_password --config-file ./test-resources/${{ matrix.cloud }}/cloudbase-init.conf 2>&1" | Tee-Object -FilePath cloudbase-init.log
        } catch {}
        $errors = $(cat ./cloudbase-init.log | Where-Object {$_ -like "*error*"})
        $pluginExecution = $(cat ./cloudbase-init.log | Where-Object {$_ -like "*Plugins execution done*"})
        if ($errors -or !$pluginExecution) {
            exit 1
        }
