name: Cloudbase-Init functional tests

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 100
      matrix:
        python-version: [3.6]
        cloud: [empty]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download external dependencies
      shell: powershell
      run: |
        git clone "https://github.com/ader1990/cloudbase-init-test-resources-1" cbs-test-res;
    - name: Install local dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt -U --force-reinstall -r requirements.txt
        pip install .
    - name: Run Cloudbase-Init
      run: |
        powershell.exe cd "cbs-test-res/${{ matrix.cloud }}/"; cloudbase-init.exe --noreset_service_password --config-file ./cloudbase-init.conf 2>&1 >> cloudbase-init.log
        powershell cat ./cloudbase-init.log
        powershell $errors = $(cat ./cloudbase-init.log ^| Where-Object {$_ -like """*error*"""}); $pluginExecution = $(cat ./cloudbase-init.log ^| Where-Object {$_ -like """*Plugins execution done*"""}); if ($errors -or !$pluginExecution) { exit 1; }
